#!/usr/bin/env python3
import subprocess
from pathlib import Path
import re

HEADER_FILE = Path("EmdBoard.h")
DEFINE_RE = re.compile(r'^(#define\s+SW_BUILD_VERSION\s+)".*?"$', re.MULTILINE)

def get_git_short_hash():
    try:
        return subprocess.check_output(["git", "rev-parse", "--short", "HEAD"], text=True).strip()
    except subprocess.CalledProcessError:
        return "UNKNOWN"

def get_git_date():
    try:
        return subprocess.check_output(["git", "show", "-s", "--format=%d.%m.%Y", "HEAD"], text=True).strip()
    except subprocess.CalledProcessError:
        return "01.01.1970"

def update_header_file(header_path, value):
    if header_path.exists():
        content = header_path.read_text()
        new_content, count = DEFINE_RE.subn(r'\1"' + value + '"', content)
        if count:
            header_path.write_text(new_content)
            return
    # If file doesn't exist or define not found, create it
    lines = [
        "#ifndef SWVERSION_H",
        "#define SWVERSION_H",
        "",
        "// Auto-generated by update_version.py",
        f'#define SW_BUILD_VERSION "{value}"',
        "",
        "#endif // SWVERSION_H"
    ]
    header_path.write_text("\n".join(lines))

def main():
    commit = get_git_short_hash()
    date = get_git_date()
    version_str = f"{commit}.{date}"
    update_header_file(HEADER_FILE, version_str)
    print(f"Updated {HEADER_FILE} -> {version_str}")

if __name__ == "__main__":
    main()
