#!/usr/bin/env python3
import subprocess
import os
import re
from pathlib import Path

# --- CONFIG ---
PROJECT_ROOT = Path(__file__).resolve().parent.parent
POSSIBLE_BOARD_FOLDERS = ["Emd _Boards", "Emd_Boards", "boards"]
BOARDS_DIR = None

for name in POSSIBLE_BOARD_FOLDERS:
    candidate = PROJECT_ROOT / name
    if candidate.exists() and candidate.is_dir():
        BOARDS_DIR = candidate
        break

if not BOARDS_DIR:
    raise FileNotFoundError(" Could not find any boards directory (e.g. 'Emd _Boards').")

DEFINE_RE = re.compile(r'(#define\s+SW_BUILD_VERSION\s+)".*"')

def get_git_version_for_board(board_dir):
    """Return the latest git hash + date for that specific board directory"""
    try:
        commit = subprocess.check_output(
            ["git", "log", "-1", "--format=%h", "--", str(board_dir)],
            text=True
        ).strip()
        date = subprocess.check_output(
            ["git", "log", "-1", "--date=format:%d.%m.%Y", "--format=%ad", "--", str(board_dir)],
            text=True
        ).strip()

        if not commit or not date:
            return "UNKNOWN.01.01.1970"

        return f"{commit}.{date}"
    except subprocess.CalledProcessError:
        return "UNKNOWN.01.01.1970"

def update_header_file(header_file, version):
    """Replace or insert SW_BUILD_VERSION define"""
    guard = os.path.basename(header_file).replace('.', '_').upper()

    if os.path.exists(header_file):
        content = open(header_file, "r").read()
        new_content, count = DEFINE_RE.subn(r'\1"' + version + '"', content)

        if count == 0:
            # Insert define before #endif if not present
            if "#endif" in content:
                new_content = content.replace(
                    "#endif",
                    f'#define SW_BUILD_VERSION "{version}"\n\n#endif'
                )
            else:
                new_content = content + f'\n#define SW_BUILD_VERSION "{version}"\n'
    else:
        # Create new file if missing
        new_content = (
            f"#ifndef {guard}\n"
            f"#define {guard}\n\n"
            f"// Auto-generated by Mult_Boards_script.py\n"
            f'#define SW_BUILD_VERSION "{version}"\n\n'
            f"#endif // {guard}\n"
        )

    with open(header_file, "w") as f:
        f.write(new_content)

def main():
    print(f"🧩 Scanning boards under: {BOARDS_DIR}\n")

    for board_dir in BOARDS_DIR.iterdir():
        if board_dir.is_dir():
            version = get_git_version_for_board(board_dir)
            print(f"{board_dir.name}: {version}")

            for header in board_dir.glob("*.h"):
                update_header_file(header, version)
                print(f"   → Updated {header.name}")

    print("\nAll board headers updated with their individual commit versions.")

if __name__ == "__main__":
    main()
