#!/usr/bin/env python3
import subprocess
import os
import re
from pathlib import Path

# --- CONFIG ---
# Automatically detect the boards directory
PROJECT_ROOT = Path(__file__).resolve().parent.parent
POSSIBLE_BOARD_FOLDERS = ["Emd _Boards", "Emd_Boards", "boards"]
BOARDS_DIR = None

for name in POSSIBLE_BOARD_FOLDERS:
    candidate = PROJECT_ROOT / name
    if candidate.exists() and candidate.is_dir():
        BOARDS_DIR = candidate
        break

if not BOARDS_DIR:
    raise FileNotFoundError(" Could not find any boards directory (e.g. 'Emd _Boards').")

# Regex to detect the SW_BUILD_VERSION line
DEFINE_RE = re.compile(r'(#define\s+SW_BUILD_VERSION\s+)".*"')

def get_git_version():
    """Return git short hash and formatted date"""
    try:
        commit = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"], text=True
        ).strip()
        date = subprocess.check_output(
            ["git", "show", "-s", "--format=%ad", "--date=format:%d.%m.%Y", "HEAD"],
            text=True
        ).strip()
        return f"{commit}.{date}"
    except subprocess.CalledProcessError:
        return "UNKNOWN.01.01.1970"

def update_header_file(header_file, version):
    """Replace or insert SW_BUILD_VERSION define"""
    guard = os.path.basename(header_file).replace('.', '_').upper()
    content = ""
    new_content = ""

    if os.path.exists(header_file):
        content = open(header_file, "r").read()
        new_content, count = DEFINE_RE.subn(r'\1"' + version + '"', content)
        if count == 0:
            # Add define before #endif
            if "#endif" in content:
                new_content = content.replace(
                    "#endif",
                    f'#define SW_BUILD_VERSION "{version}"\n\n#endif'
                )
            else:
                new_content = content + f'\n#define SW_BUILD_VERSION "{version}"\n'
    else:
        # Create new file if not found
        new_content = (
            f"#ifndef {guard}\n"
            f"#define {guard}\n\n"
            f"// Auto-generated by Mult_Boards_script.py\n"
            f'#define SW_BUILD_VERSION "{version}"\n\n'
            f"#endif // {guard}\n"
        )

    with open(header_file, "w") as f:
        f.write(new_content)

def main():
    version = get_git_version()
    print(f"🔍 Detected version: {version}\n")

    headers_updated = []
    for board_dir in BOARDS_DIR.iterdir():
        if board_dir.is_dir():
            for header in board_dir.glob("*.h"):
                update_header_file(header, version)
                headers_updated.append(header)

    if headers_updated:
        print(" Updated version in the following headers:")
        for h in headers_updated:
            print(f"   → {h}")
    else:
        print(" No header files found in:", BOARDS_DIR)

if __name__ == "__main__":
    main()
